/**
 * Every Centrelink in Greater Sydney, at the coordinates OSM has for it.
 *
 * **Generated by `scripts/centrelinks.py`. Do not edit by hand** -- the next
 * run overwrites it, and the position of a government office is a fact about
 * Sydney rather than a decision this repo gets to make. 31 offices within
 * 60000 m of Town Hall: 23 read out of the OSM extract and 8
 * from the script's hand-looked-up backstop, which fills in only where the
 * extract had nothing within 60 m. See the script's header for the tag filter,
 * the deduplication rule and why this is a checked-in table rather than a
 * per-tile sidecar like every other point feature in the project.
 *
 * `x` is east metres and `z` is south metres from the Town Hall origin, which
 * is the same frame everything else in `game/` speaks. There is deliberately no
 * `y`: the ground under a claim point is queried at runtime on whichever end is
 * asking, because the server's `groundFor` and the client's composed ground
 * query are the one pair of things in this project that must agree, and a baked
 * height would be a third opinion.
 *
 * Imported by `game/cash.ts` (the claim rule), by the phone's Centrelink app,
 * and by both maps' markers. Three-free, so the server reads the same table.
 */

/** One service centre. `source` is provenance and nothing reads it but a check. */
export interface CentrelinkOffice {
  /** Stable for the life of the table; what a claim record is keyed on. */
  readonly id: string;
  readonly name: string;
  /** World metres, east and south of Town Hall. */
  readonly x: number;
  readonly z: number;
  readonly source: 'osm' | 'manual';
}

export const CENTRELINKS: readonly CentrelinkOffice[] = [
  { id: 'cl000', name: 'Centrelink', x: -27037.8, z: -19682.3, source: 'osm' },
  { id: 'cl001', name: 'Medicare', x: -10565.4, z: -17826.7, source: 'osm' },
  { id: 'cl002', name: 'Centrelink', x: -48272.4, z: -11977.2, source: 'osm' },
  { id: 'cl003', name: 'Centrelink Brookvale', x: 5594.0, z: -11747.0, source: 'osm' },
  { id: 'cl004', name: 'Centrelink', x: 5020.8, z: -11453.0, source: 'osm' },
  { id: 'cl005', name: 'Centrelink', x: -40380.8, z: -10882.8, source: 'osm' },
  { id: 'cl006', name: 'Centrelink', x: -27811.9, z: -10617.9, source: 'osm' },
  { id: 'cl007', name: 'Centrelink', x: -35953.0, z: -10397.1, source: 'osm' },
  { id: 'cl008', name: 'Centrelink Chatswood', x: -2759.3, z: -7949.7, source: 'manual' },
  { id: 'cl009', name: 'Centrelink', x: -9913.3, z: -5871.0, source: 'osm' },
  { id: 'cl010', name: 'Services Australia', x: -19406.2, z: -5366.4, source: 'osm' },
  { id: 'cl011', name: 'Services Australia', x: -20221.3, z: -3308.4, source: 'osm' },
  { id: 'cl012', name: 'Centrelink Auburn', x: -16350.4, z: -1853.3, source: 'manual' },
  { id: 'cl013', name: 'Centrelink', x: -23675.3, z: 885.8, source: 'osm' },
  { id: 'cl014', name: 'Centrelink Burwood', x: -9723.1, z: 1150.6, source: 'manual' },
  { id: 'cl015', name: 'Centrelink', x: -4580.0, z: 2106.9, source: 'osm' },
  { id: 'cl016', name: 'Centrelink Bondi Junction', x: 3770.3, z: 2419.8, source: 'manual' },
  { id: 'cl017', name: 'Centrelink Redfern', x: -925.2, z: 2645.2, source: 'manual' },
  { id: 'cl018', name: 'Centrelink', x: -25369.3, z: 3460.4, source: 'osm' },
  { id: 'cl019', name: 'Services Australia', x: -3346.4, z: 4223.2, source: 'osm' },
  { id: 'cl020', name: 'Centrelink Marrickville', x: -4910.6, z: 4812.6, source: 'manual' },
  { id: 'cl021', name: 'Centrelink Campsie', x: -9802.9, z: 4855.1, source: 'osm' },
  { id: 'cl022', name: 'Centrelink Bankstown', x: -16066.3, z: 5740.7, source: 'manual' },
  { id: 'cl023', name: 'Centrelink Liverpool Service Centre', x: -26451.7, z: 6561.8, source: 'osm' },
  { id: 'cl024', name: 'Centrelink', x: -6565.7, z: 9238.2, source: 'osm' },
  { id: 'cl025', name: 'Centrelink Hurstville', x: -9658.8, z: 11133.8, source: 'manual' },
  { id: 'cl026', name: 'Centrelink', x: -31254.4, z: 14926.5, source: 'osm' },
  { id: 'cl027', name: 'Centrelink', x: -13543.9, z: 18319.4, source: 'osm' },
  { id: 'cl028', name: 'Centrelink', x: -7775.4, z: 19437.7, source: 'osm' },
  { id: 'cl029', name: 'Centrelink', x: -47172.8, z: 21744.8, source: 'osm' },
  { id: 'cl030', name: 'Services Australia', x: -35831.1, z: 22489.1, source: 'osm' },
];
