/**
 * How busy a place is, from the census, as one multiplier on everything alive.
 *
 * The player: *"weight number of people and cars by density stats from nsw
 * govt, with a 20% higher max, scaling all the way down to 5% of the max in
 * places like dural"*.
 *
 * Before this, `pedestrians.SLOT_DENSITY` and the baked `.lanes.bin` headways
 * were the same everywhere inside a 60 km disc. A Dural cul-de-sac scheduled
 * the same walkers per metre of footpath as Crown Street, and the Old Northern
 * Road ran the same timetable as Parramatta Road. Class weighting hid some of
 * it -- the retail strips really are the classified roads in the inner city --
 * but class says nothing at all about *where in Sydney you are*, and so the
 * middle ring and the fringe both came out reading like the inner west.
 *
 * ---------------------------------------------------------------------------
 * WHAT THE FIELD IS
 *
 * `density-data.ts` is 248 x 248 bytes over a 500 m grid covering the whole
 * built extent, generated by `scripts/density.py` from ABS 2021 Census resident
 * counts on ASGS 2021 SA1 boundaries. Each byte is a **geometric rank** in
 * `[0, 255]` and this file turns it into a multiplier:
 *
 *     m = MUL_MIN * (MUL_MAX / MUL_MIN) ** (rank / 255)
 *
 * so every step of the byte is the same 1.25% *ratio* rather than the same
 * amount. That split is deliberate. The bytes carry the geography and nothing
 * else; the curve -- which percentile is 1.2x, how steep the fall to 0.05x is
 * -- lives here in eight lines that can be retuned without refetching 12,105
 * polygons. It also means the client and the Bun server cannot disagree about
 * what a byte means, because there is exactly one place that decides.
 *
 * The census half of the shape is argued in `scripts/density.py`. The short
 * version: a power law, `m = 1.2 * (d / 7,109) ** 0.79`, pinned at the top to
 * the 99.5th percentile of populated cells and at the bottom to Dural itself,
 * which is the place the brief named. It is a power law rather than a linear
 * map because resident density here spans four orders of magnitude, and a
 * linear map would put every suburb from Ryde to Penrith inside the bottom two
 * per cent of the range -- the same "everywhere outside the CBD is identical"
 * failure the brief is complaining about, with the sign flipped.
 *
 * ---------------------------------------------------------------------------
 * IT IS READ AT RUNTIME, AND THE WORLD DID NOT HAVE TO BE REBUILT
 *
 * Both consumers already run a per-tile decode on both ends:
 * `pedestrians.buildBands` turns a ways block into footpath bands and
 * `traffic.decodeLanes` turns a routes block into timetables. Both are pure
 * functions of the same bytes on the client and the server. Scaling inside
 * those two functions is therefore automatically consistent across the wire,
 * costs one grid read per band and per route at tile-decode time, and needed
 * nothing rebaked -- a `.lanes.bin` from the shipped world produces a busy
 * Redfern and an empty Dural out of the identical file.
 *
 * ---------------------------------------------------------------------------
 * CARS ARE NOT PEOPLE
 *
 * A quiet street in Dural still has cars parked along it and the M2 through
 * Dural is full at eight in the morning, neither of which has anything to do
 * with how many people live within a kilometre. So traffic reads
 * `trafficMultiplier`, not `crowdMultiplier`, and that is the crowd figure
 * floored by `CLASS_FLOOR` -- what a road of this class carries because of what
 * it is rather than because of who lives near it. A motorway never drops below
 * 1.0 anywhere; a residential street never drops below 0.12, which is one car
 * in eight rather than none.
 *
 * The static parked fleet in `.cars.bin` is deliberately **not** touched. Those
 * cars are scenery, they are the thing the brief explicitly says a Dural street
 * still has, and thinning them would empty the kerbs of the exact suburbs where
 * every house has two cars and a boat.
 */

import { DENSITY_PACKED } from './density-data.ts';

// --- The grid ------------------------------------------------------------------

/** Cell edge, metres. `config.TILE_SIZE`, so a cell is a tile. */
export const DENSITY_CELL_M = 500;

/**
 * Half the grid's span, metres.
 *
 * The terrain lattice reaches +/-60,500 m, so 62,000 clears the built world
 * with a cell and a half to spare and the clamp below never fires anywhere a
 * player can stand. Must match `scripts/density.py`'s `HALF_EXTENT_M`;
 * `verifyDensity` checks the two agree by checking the byte count.
 */
export const DENSITY_HALF_EXTENT_M = 62000;

/** Cells per side. `2 * HALF_EXTENT / CELL`. */
export const DENSITY_GRID = 248;

/**
 * The player's two numbers, and the only two numbers in this feature that were
 * chosen rather than measured.
 *
 * 1.2x at the top -- "a 20% higher max" -- and 0.05x at the bottom, "5% of the
 * max in places like dural". A 24:1 spread. `scripts/density.py` holds the same
 * pair and the generated header records the fit that was made against them; a
 * disagreement would show up as a field whose extremes are not these, which is
 * what `verifyDensity` asserts.
 */
export const MUL_MIN = 0.05;
export const MUL_MAX = 1.2;

/** `MUL_MAX / MUL_MIN`, precomputed. The whole dynamic range, 24. */
const MUL_SPAN = MUL_MAX / MUL_MIN;
const LN_SPAN = Math.log(MUL_SPAN);

/**
 * The grid, unpacked once.
 *
 * `atob` rather than a `Buffer` or a hand-rolled decoder: it exists in the
 * browser, in Bun and in Node 22, which is every process that loads this file,
 * and 61,504 bytes at module load is under a millisecond. Indexed
 * `ix * DENSITY_GRID + iz`, x-major, which is the order `scripts/density.py`
 * writes.
 */
const FIELD: Uint8Array = (() => {
  const bin = atob(DENSITY_PACKED);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
})();

/** The raw rank byte at a cell, clamped to the grid. Zero outside it. */
function rankAt(ix: number, iz: number): number {
  if (ix < 0) ix = 0;
  else if (ix >= DENSITY_GRID) ix = DENSITY_GRID - 1;
  if (iz < 0) iz = 0;
  else if (iz >= DENSITY_GRID) iz = DENSITY_GRID - 1;
  return FIELD[ix * DENSITY_GRID + iz];
}

/**
 * How busy this patch of ground is, as a multiplier on the uniform rate.
 *
 * Bilinear between the four surrounding **cell centres**, on the rank rather
 * than on the multiplier -- which, because the rank is a log, makes it a
 * *geometric* interpolation of the multiplier. That is the right one: halfway
 * between a 1.2x cell and a 0.05x cell should read 0.24x, the way a fringe
 * reads, not 0.63x.
 *
 * Interpolating at all rather than reading the containing cell is not
 * cosmetic. A nearest-cell read puts a visible 500 m checkerboard across the
 * middle ring, where one street has a crowd and the parallel street two blocks
 * over has none for no reason a player can see, and it puts that seam exactly
 * on the tile boundaries -- so it would read as a streaming bug rather than as
 * a suburb.
 */
export function crowdMultiplier(x: number, z: number): number {
  // Cell centre i sits at -HALF + (i + 0.5) * CELL, so the continuous cell
  // coordinate of a point is this, and the floor of it is the lower neighbour.
  const u = (x + DENSITY_HALF_EXTENT_M) / DENSITY_CELL_M - 0.5;
  const w = (z + DENSITY_HALF_EXTENT_M) / DENSITY_CELL_M - 0.5;
  const i0 = Math.floor(u);
  const k0 = Math.floor(w);
  const fx = u - i0;
  const fz = w - k0;
  const r00 = rankAt(i0, k0);
  const r10 = rankAt(i0 + 1, k0);
  const r01 = rankAt(i0, k0 + 1);
  const r11 = rankAt(i0 + 1, k0 + 1);
  const top = r00 + (r10 - r00) * fx;
  const bot = r01 + (r11 - r01) * fx;
  const rank = top + (bot - top) * fz;
  return MUL_MIN * Math.exp((rank / 255) * LN_SPAN);
}

// --- Roads ---------------------------------------------------------------------

/**
 * The floor a road of each class gets whatever the census says, indexed by the
 * class byte in `.lanes.bin`.
 *
 * **Must be `traffic.LANE_CLASSES.length` long**, in that order. `verifyTraffic`
 * hands that length to `verifyDensity` rather than this module importing it,
 * because the dependency runs the other way: `traffic.ts` imports *this*, and a
 * cycle between a decoder and the table it reads is the kind of thing that
 * works until a bundler reorders two modules.
 *
 * These are not measured, they are the answer to one question: if nobody lived
 * anywhere near this road, how much of today's traffic would still be on it?
 * For a motorway the answer is all of it -- the M2 exists to carry people
 * *through* the Hills district and is at its worst where nobody lives. For a
 * residential street the answer is nearly none, but not none: 0.12 is one car
 * in eight, which is a car every couple of minutes rather than an empty street,
 * and an empty street is a worse lie than a quiet one.
 *
 * The link ramps sit just under their parent class rather than at zero: a ramp
 * carries what the road it serves carries. They have no footpath bands at all
 * (`pedestrians.SLOT_DENSITY` zeroes them) but they very much have cars.
 */
export const CLASS_FLOOR: readonly number[] = [
  1.0,   // motorway        -- the M2 through Dural is full at 8 a.m.
  0.9,   // motorway_link
  0.85,  // trunk           -- Pacific Highway, Windsor Road
  0.75,  // trunk_link
  0.6,   // primary
  0.55,  // primary_link
  0.45,  // secondary
  0.4,   // secondary_link
  0.3,   // tertiary
  0.28,  // tertiary_link
  0.12,  // residential     -- a car every couple of minutes, not none
  0.12,  // unclassified
  0.1,   // living_street
  0.06,  // service         -- a laneway, occasionally
  0.1,   // other
];

/**
 * How much traffic this road carries, as a multiplier on the baked timetable.
 *
 * `max` of the crowd figure and the class floor rather than a blend, and the
 * reason is that the two are alternative explanations for the same car rather
 * than contributions to it. A car on the M2 at Dural is there because it is the
 * M2; a car on a Surry Hills terrace street is there because somebody who lives
 * there owns it. Adding them would double-count the CBD's arterials, which are
 * both; taking the larger says "whichever reason is the bigger one, that is how
 * busy this is", and never exceeds the 1.2x ceiling.
 */
export function trafficMultiplier(x: number, z: number, klass: number): number {
  const floor = CLASS_FLOOR[klass] ?? CLASS_FLOOR[CLASS_FLOOR.length - 1];
  const m = crowdMultiplier(x, z);
  return m > floor ? m : floor;
}

/**
 * A crowd function that says "average everywhere", for self-checks.
 *
 * `buildBands` and `decodeLanes` take their crowd function as a defaulted
 * parameter purely so that this can be passed in. Every real caller uses the
 * default and no code path outside a `verify*` ever supplies anything else --
 * the injection point exists so the *other* checks can go on testing what they
 * were written to test.
 *
 * The alternative was to move the synthetic street to a spot on the grid where
 * the field happens to read 1.0, which would have made twenty assertions in
 * `verifyTraffic` and `verifyPedestrians` silently depend on the census not
 * changing at that coordinate. Those checks are about the *format*: whether a
 * band lands on the correct side of a kerb, whether a car goes backwards
 * through a pull-out, whether two decodes of one file agree. None of them has
 * an opinion about Dural, and none of them should start failing because the ABS
 * published a new release.
 *
 * The scaling itself is checked separately and deliberately, against the real
 * default, by the sections in both files that decode one sidecar at Redfern's
 * coordinates and again at Dural's.
 */
export const UNIFORM_CROWD = (): number => 1;

// --- Named places, for the check and for anyone reading -------------------------

/**
 * Where the field is asserted, in world metres.
 *
 * The coordinates are `game/streetlife.SUBURBS`' own, which came out of the
 * same OSM extract through the same projection, so these rows test the *field*
 * rather than testing two projections against each other. The bands are wide --
 * this is a guard against the grid being blank, mis-scaled, transposed or
 * offset, not a regression test on the census.
 *
 * The ordering assertion below them is the one that matters. A field that came
 * out constant -- a fetch that failed into zeros, a base64 that decoded to
 * nothing, an index that transposed x and z -- passes every "is the multiplier
 * in range" test there is, and is exactly the failure this whole feature
 * consists of not having.
 */
const PROBES: ReadonlyArray<{ name: string; x: number; z: number; lo: number; hi: number }> = [
  { name: 'Haymarket', x: -423.9, z: 1409.6, lo: 1.05, hi: 1.2 },
  { name: 'Redfern', x: -440.5, z: 2703.8, lo: 1.0, hi: 1.2 },
  { name: 'Surry Hills', x: 97.9, z: 1741.3, lo: 1.0, hi: 1.2 },
  { name: 'Sydney CBD', x: 35.7, z: -3.9, lo: 0.9, hi: 1.2 },
  { name: 'Parramatta', x: -18749.1, z: -5638.4, lo: 0.8, hi: 1.2 },
  { name: 'Hornsby', x: -10394.0, z: -18092.6, lo: 0.6, hi: 1.15 },
  { name: 'Penrith', x: -47948.9, z: -12089.7, lo: 0.25, hi: 0.75 },
  { name: 'Dural', x: -15230.7, z: -20051.7, lo: 0.05, hi: 0.12 },
  { name: 'Middle Dural', x: -18206.6, z: -25231.5, lo: 0.05, hi: 0.12 },
];

/** The multiplier at each named place. Diagnostics; `checkDensity` prints it. */
export function namedMultipliers(): Array<{ name: string; multiplier: number }> {
  return PROBES.map((p) => ({ name: p.name, multiplier: crowdMultiplier(p.x, p.z) }));
}

/**
 * The whole feature's arithmetic, against the shipped grid.
 *
 * Nine sections, and the ones with teeth are 3, 4 and 7: they are the negative
 * controls. Everything else here would still pass against a field of identical
 * bytes, and a field of identical bytes is precisely the bug -- the placement
 * would go on being uniform and nothing but a screenshot of Dural would say so.
 */
export function verifyDensity(laneClassCount?: number): string[] {
  const failures: string[] = [];

  // --- 1. The grid is the size both ends think it is.
  if (FIELD.length !== DENSITY_GRID * DENSITY_GRID) {
    failures.push(
      `The packed field decoded to ${FIELD.length} bytes; a ${DENSITY_GRID} x ${DENSITY_GRID} ` +
        `grid is ${DENSITY_GRID * DENSITY_GRID}. The generated file and this module disagree.`,
    );
    return failures;
  }
  if (DENSITY_GRID * DENSITY_CELL_M !== 2 * DENSITY_HALF_EXTENT_M) {
    failures.push(
      `${DENSITY_GRID} cells of ${DENSITY_CELL_M} m span ${DENSITY_GRID * DENSITY_CELL_M} m, ` +
        `not the ${2 * DENSITY_HALF_EXTENT_M} m the half-extent claims.`,
    );
  }

  // --- 2. Every reading is inside the brief's two numbers, including outside
  // the grid, where the clamp has to hold rather than return NaN.
  const corners: Array<[number, number]> = [
    [0, 0], [61000, 61000], [-61000, -61000], [61000, -61000], [-61000, 61000],
    [200000, 0], [0, -200000], [-1e9, 1e9],
  ];
  for (const [x, z] of corners) {
    const m = crowdMultiplier(x, z);
    if (!(m >= MUL_MIN - 1e-9 && m <= MUL_MAX + 1e-9)) {
      failures.push(`The multiplier at (${x}, ${z}) is ${m}; it must be in [${MUL_MIN}, ${MUL_MAX}].`);
    }
  }

  // --- 3. NEGATIVE CONTROL: the field is not constant. The single failure this
  // feature is most likely to ship -- a blank fetch, a base64 that decoded to
  // zeros, a build that wrote the wrong array -- looks exactly like the feature
  // working, from every angle except a screenshot of Dural.
  let lo = 255;
  let hi = 0;
  let nonZero = 0;
  for (let i = 0; i < FIELD.length; i++) {
    const b = FIELD[i];
    if (b < lo) lo = b;
    if (b > hi) hi = b;
    if (b > 0) nonZero++;
  }
  if (hi - lo < 200) {
    failures.push(
      `The field's ranks run ${lo}..${hi}, a span of ${hi - lo} out of 255. It is nearly ` +
        `constant, which means the placement is still uniform and the whole feature is inert.`,
    );
  }
  if (nonZero < 5000 || nonZero > 55000) {
    failures.push(
      `${nonZero} of ${FIELD.length} cells carry any population. Sydney inside 60 km should ` +
        `light up roughly 20,000-40,000 of them; this is either a blank grid or a saturated one.`,
    );
  }

  // --- 4. NEGATIVE CONTROL: the ordering is Sydney's, not an arbitrary one. A
  // transposed index or a sign flip on z produces a field with a perfectly
  // healthy histogram that happens to describe a different city.
  const m = new Map(namedMultipliers().map((r) => [r.name, r.multiplier]));
  const order = ['Redfern', 'Parramatta', 'Hornsby', 'Penrith', 'Dural'];
  for (let i = 0; i + 1 < order.length; i++) {
    const a = m.get(order[i]) ?? 0;
    const b = m.get(order[i + 1]) ?? 0;
    if (!(a > b)) {
      failures.push(
        `${order[i]} reads ${a.toFixed(3)} and ${order[i + 1]} reads ${b.toFixed(3)}. The field ` +
          `should fall monotonically along ${order.join(' > ')}; it does not, so it is not ` +
          `describing Sydney -- suspect a transposed or mirrored grid index.`,
      );
      break;
    }
  }
  const redfern = m.get('Redfern') ?? 0;
  const dural = m.get('Dural') ?? 1;
  if (!(redfern / dural > 8)) {
    failures.push(
      `Redfern is only ${(redfern / dural).toFixed(1)}x Dural. The brief asks for 24x between ` +
        `the extremes and Redfern is near the top, so anything under 8x means the curve has ` +
        `flattened and Dural still feels like Redfern.`,
    );
  }

  // --- 5. The named places are where they should be. Wide bands -- this is a
  // guard against an offset grid, not a regression test on the ABS.
  for (const p of PROBES) {
    const v = crowdMultiplier(p.x, p.z);
    if (!(v >= p.lo && v <= p.hi)) {
      failures.push(
        `${p.name} reads ${v.toFixed(3)}x; expected ${p.lo}..${p.hi}. Either the grid is offset ` +
          `from the world frame or the curve has been retuned without updating this band.`,
      );
    }
  }

  // --- 6. The interpolation is continuous and lands on the cell value at a
  // cell centre. A bilinear that is off by half a cell puts every suburb 250 m
  // from where it is, which is invisible until it is Dural's crowd on Redfern's
  // streets.
  for (let i = 4; i < DENSITY_GRID; i += 37) {
    const cx = -DENSITY_HALF_EXTENT_M + (i + 0.5) * DENSITY_CELL_M;
    for (let k = 7; k < DENSITY_GRID; k += 41) {
      const cz = -DENSITY_HALF_EXTENT_M + (k + 0.5) * DENSITY_CELL_M;
      const want = MUL_MIN * Math.exp((rankAt(i, k) / 255) * LN_SPAN);
      const got = crowdMultiplier(cx, cz);
      if (Math.abs(got - want) > 1e-9) {
        failures.push(
          `At the centre of cell (${i}, ${k}) the interpolation gives ${got} and the cell holds ` +
            `${want}. The bilinear is off by half a cell.`,
        );
        i = DENSITY_GRID;
        break;
      }
    }
  }
  // Continuity across a cell boundary: a step here is the 500 m checkerboard.
  {
    const bx = -DENSITY_HALF_EXTENT_M + 100 * DENSITY_CELL_M;
    const before = crowdMultiplier(bx - 1e-4, 2000);
    const after = crowdMultiplier(bx + 1e-4, 2000);
    if (Math.abs(before - after) > 1e-6) {
      failures.push(`The field steps by ${Math.abs(before - after)} across a cell boundary at x=${bx}.`);
    }
  }

  // --- 7. NEGATIVE CONTROL for the traffic half: a motorway must not follow
  // the census and a residential street must. If `trafficMultiplier` collapsed
  // to `crowdMultiplier` the fringe motorways would empty, and if it collapsed
  // to the floor the whole city would be uniform again -- two opposite bugs
  // that this one comparison catches both of.
  const duralX = -15230.7;
  const duralZ = -20051.7;
  const motorway = trafficMultiplier(duralX, duralZ, 0);
  const local = trafficMultiplier(duralX, duralZ, 10);
  if (!(motorway >= 0.95)) {
    failures.push(
      `A motorway at Dural carries ${motorway.toFixed(3)}x. Road class is supposed to floor it ` +
        `near 1.0 regardless of who lives there; traffic has been tied to the census alone.`,
    );
  }
  if (!(local <= 0.2)) {
    failures.push(
      `A residential street at Dural carries ${local.toFixed(3)}x. The class floor is meant to be ` +
        `a floor, not a level -- a quiet suburb should still be quiet.`,
    );
  }
  const cbdLocal = trafficMultiplier(35.7, -3.9, 10);
  if (!(cbdLocal > local * 4)) {
    failures.push(
      `A residential street reads ${cbdLocal.toFixed(3)}x in the CBD and ${local.toFixed(3)}x at ` +
        `Dural. The class floor has swamped the census and traffic is uniform again.`,
    );
  }

  // --- 8. Every floor is a legal multiplier, and the table is the right shape.
  if (laneClassCount !== undefined && CLASS_FLOOR.length !== laneClassCount) {
    failures.push(
      `CLASS_FLOOR has ${CLASS_FLOOR.length} entries and there are ${laneClassCount} lane classes.`,
    );
  }
  for (let i = 0; i < CLASS_FLOOR.length; i++) {
    const f = CLASS_FLOOR[i];
    if (!(f >= MUL_MIN && f <= MUL_MAX)) {
      failures.push(`CLASS_FLOOR[${i}] is ${f}, outside [${MUL_MIN}, ${MUL_MAX}].`);
    }
  }
  // A motorway must outrank a residential street, or the table has been sorted.
  if (!(CLASS_FLOOR[0] > CLASS_FLOOR[10] && CLASS_FLOOR[10] > CLASS_FLOOR[13])) {
    failures.push(
      `CLASS_FLOOR is not ordered motorway > residential > service ` +
        `(${CLASS_FLOOR[0]}, ${CLASS_FLOOR[10]}, ${CLASS_FLOOR[13]}); the table has been reordered.`,
    );
  }

  // --- 9. The extremes really are reachable. The brief's 1.2x and 0.05x should
  // both exist somewhere on the grid, or the range is being wasted.
  if (lo !== 0) {
    failures.push(`The lowest rank on the grid is ${lo}, not 0; nothing anywhere reads ${MUL_MIN}x.`);
  }
  if (hi !== 255) {
    failures.push(`The highest rank on the grid is ${hi}, not 255; nothing anywhere reads ${MUL_MAX}x.`);
  }

  return failures;
}
